### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by mpizenberg** [elm-tooling/elm-tooling-cli#17]
I see that tests are mentioned in the spec. elm-test-rs could fit well with elm-tooling since it is an executable not depending on npm. In such cases, a tests section could be used directly if present. However, by default the command line expects files as arguments, not directories. I can see two convenient ways to spec it. Either globs are authorized in the tests section, or only directories, and the tests runner convert those automatically to something like `dir1/*.elm dir2/*.elm ...`

**Comment by lydell** [comment]
The _ideal_ solution is to have no configuration at all: Running just `elm-test` or `elm-test-rs` should run _all_ tests, no matter where they are located, without any config.

This is already possible. Instead of defaulting to `tests/`, we just need to default to all source directories, plus `tests/` if it exists.

So why don’t we do that already? Because of performance. I tried this at work, and the compiled JS becomes megabytes, which is parsed over and over in different workers.

I think we should see what it would take to make the no-config approach possible. If it isn’t possible – or it’s too far in the future – I guess we could still add a field in the mean time.

As a side note: IDEs. They could work without config, too:

- For packages, allow test-dependencies in any files not in `exposed-modules` (easy).
- For applications, allow values from test-dependencies only in values not reachable from any entrypoint (harder).

**Comment by mpizenberg** [comment]
> Either globs are authorized in the tests section, or only directories

I don't know why I was thinking that, having both files and directories would be fine if a tests field is created.

> So why don’t we do that already? Because of performance. I tried this at work, and the compiled JS becomes megabytes, which is parsed over and over in different workers.

Is this because "potential" tests are coming from almost all files? If there was type inference and only actual test values are picked, would the generated file be lighter?

**Comment by lydell** [comment]
> Do you have an example public repo where this problem appears?

Not off the top of my head. I’ll try to look for one.

> Is this because "potential" tests are coming from almost all files?

At work, we only have tests in the `tests/` folder.

`elm-test tests` results in a 1.2 MB JS file.

`elm-test tests src` results in a 5.8 MB JS file – it’s _all_ of our Elm code in there (even stuff that’s never reached from tests). Like you say, this is because the no-elmi approach we currently have requires compiling _all_ given Elm code to JS, because we don’t know what could be tests until runtime.

> If there was type inference and only actual test values are picked, would the generated file be lighter?

Yes. Then it would go down to 1.2 MB again. I tested this – node-test-runner@0.19.1-revision4 works that way. It results in a 1.2 MB file even when running `elm-test tests src`. That’s because `elmi-to-json` knows which modules contain `Test` values so we only compile those to JS.

I’ve been toying with the idea of doing partial type inference the last couple of days. Sounds like a fun project, but I’m unsure when I’ll get time to experiment with it.

**Comment by Razzeee** [comment]
> This is already possible. Instead of defaulting to tests/, we just need to default to all source directories, plus tests/ if it exists.

Becomes "tests/ + files that have anything typed `Test`" when we have type inference? 
I'm asking, cause we need to figure out how to import the deps of test files a bit more correct. See: https://github.com/elm-tooling/elm-language-server/issues/589

**Comment by lydell** [comment]
> Becomes "tests/ + files that have anything typed `Test`" when we have type inference?

Yes. I’m thinking the algorithm would be:

1. Find all .elm files in source-directories plus tests/ if it exists.
2. In those files, find all _exposed_ values of type `Test`.
3. That’s all the tests.

**Comment by lydell** [comment]
`elm-tooling.json` is no longer a shared config file: https://github.com/elm-tooling/elm-tooling-cli/pull/77

So this discussion does not belong here anymore.

Note: https://github.com/elm-tooling/elm-language-server/pull/629 implements quite good test detection: Some files are tests for sure, some files are _not_ tests for sure and some files _could_ be tests. I’d like to explore having `elm-test` and `elm-test-rs` default to “tests for sure + possibly tests” instead of `tests/`, and as such avoiding configuration altogether. Or come up with something that isn’t so complicated for tools.
